apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: onlineeventbooking-danish
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=        # 'password'
  RABBITMQ_PASSWORD: Z3Vlc3Q=            # 'guest'
  EMAIL_PASS: bHBheXh1d3RlcmZtcWppeA==   # your base64 encoded Gmail App Password